export const BUTTONS_FILTER=[
    {
       title:'Promos',
       value:'promos' 
    },
    {
        title:'Combos',
        value:'combos' 
     },
     {
        title:'Cafes',
        value:'cafes' 
     },
     {
        title:'Dulces',
        value:'dulces' 
     },
     {
        title:'Salados',
        value:'salados' 
     },
]